### ISSUE TITLE
Create Mockups for Additional Pages

### ISSUE THREAD

**Issue by kanoaaaa** [hawaii-bites/hawaii-bites-project#3]
Do all work for this task in a branch called issue-3.
Develop mockups for the following pages using placeholder content:

Today's Top Picks: Highlights popular food options based on user preferences.
Foods Available Right Now: Displays real-time availability of food items on campus.
User Profile: Dashboard for users to set preferences and view saved items.
Menu: A categorized list of available food items by cuisine or vendor.
These mockups will be used to guide the development of the full pages in later milestones.

**Comment by sethines** [comment]
This was done before M1 was created so the mockup pages are in the main branch instead of the issues-3 branch.
