### ISSUE TITLE
Create and deploy the Vercel project

### ISSUE THREAD

**Issue by kanoaaaa** [hawaii-bites/hawaii-bites-project#5]
Do all work for this task in a branch called issue-1.
Set up a new Vercel project for the hawaii-bites.github.io repository. Connect the Next.js application to Vercel and deploy it. Verify that the deployment URL (e.g., https://hawaii-bites.vercel.app) is publicly accessible. This task must be completed first to allow testing on the live environment.

**Comment by sethines** [comment]
Completed in the issues-1 branch.
